### ISSUE TITLE
`dune build` failed after `opam monorepo pull`

### ISSUE THREAD

**Issue by favonia** [ocamllabs/opam-monorepo#149]
The `dune` seems to be confused by the (intentionally) broken `dune-project` files after `opam monorepo pull` pulls in all the dependencies.
```
File "duniverse/dune_/test/blackbox-tests/test-cases/dialects.t/bad1/dune-project", line 9, characters 1-74:
 9 |  (name d)
10 |  (implementation (extension foo2))
11 |  (interface (extension bar2)))
Error: dialect "d" is already defined
```
(I am not completely sure where to report this---but I suppose it is okay to report the issue here.)

**Comment by NathanReb** [comment]
Thanks for reporting this!

It is a known bug in dune, it has been reported [here](https://github.com/ocaml/dune/issues/4001) and fixed upstream but not released yet unfortunately.

The bug is in the host `dune`, i.e. the one installed locally. Once the fix is released, upgrading your local dune should solve this issue. In the meantime the workaround is either to remove the problematic test from the vendored `dune_` folder by running:
```
rm -r duniverse/dune_/test/blackbox-tests/
```
or to make sure you vendor a version of the repo that doesn't contain this test by adding the following conflict to your opam file:
```
conflicts: [
  "dune-build-info" {= "2.7.0" | = "2.7.1"}
  "dune-configurator" {= "2.7.0" | = "2.7.1"}
]
```
and running `opam monorepo lock` and `opam monorepo pull` again.

**Comment by NathanReb** [comment]
I'm closing this but please don't hesitate to re-open or to reach out if the proposed workaround don't work for you for some reason!
