### ISSUE TITLE
Wrong behavior when locking a single package

### ISSUE THREAD

**Issue by TheLortex** [ocamllabs/opam-monorepo#162]
When locking specific packages, a different behavior exists depending on the number of packages locked:
- a single package `xxx` generates `xxx.opam.locked`
- multiple packages generates `<project name>.opam.locked`

In the first case, a subsequent `opam monorepo pull` would fail as it looks for `<project name>.opam.locked` to perform the pull.

**Comment by NathanReb** [comment]
Thanks for reporting this, it should indeed be fixed.

I'll open a PR shortly changing it so that:
1. When infering the lockfile path, always use the project name as defined in the `dune-project` file and gracefully exit when it is not defined
2. We provide a `-l`/`--lockfile` CLI option where you can set the path to the lockfile yourself to make the tool a bit more flexible

Does that sound good?

**Comment by TheLortex** [comment]
Yes. My specific use case is that doing `opam monorepo lock <specific package> && opam monorepo pull` fails, so your proposal fixes my issue !
